name: easal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  # flutter_side_menu: ^0.4.0
  easy_sidemenu: ^0.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1 
  fpdart: ^1.1.0
  pocketbase: ^0.14.1
  injectable: ^2.3.0
  get_it: ^7.6.0
  auto_route: ^7.8.3
  shared_preferences: ^2.2.0
  logger: ^2.0.1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.1
  loader_overlay: ^2.3.2
  flutter_spinkit: ^5.2.0
  side_sheet: ^1.0.4
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  printing: ^5.11.0
  pdf: ^3.10.4
  fluttertoast: ^8.2.2
  file_saver: ^0.2.8
  excel: ^2.1.0
  path: ^1.8.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4
  flutter_launcher_icons: ^0.13.1



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/


flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/receipts.png"
    icon_size: 48 # min:48, max:256, default: 48